### ISSUE TITLE
Not compatible with MM 2.20

### ISSUE THREAD

**Issue by docn85** [niklaskappler/MMM-vvsDeparture#17]
Hello,

after setting up a new Mirror i encounterd issue i want to point out.

MM is not able to start when you have pulled the module and configured the config.js
see as follows:
```
[ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-vvsDeparture/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js


[08.08.2022 01:50.58.268] [ERROR] App threw an error during load
[08.08.2022 01:50.58.275] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-vvsDeparture/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-vvsDeparture/node_helper.js:10:15)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
[08.08.2022 01:50.58.283] [ERROR] Whoops! There was an uncaught exception...
[08.08.2022 01:50.58.319] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-vvsDeparture/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-vvsDeparture/node_helper.js:10:15)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-vvsDeparture/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
```
A workaround to load the module is when you navigate to the directory of the MMM-vvsDeparture-Module and execute the command `npm install request`.
By renewing the packages.js, this issue could be solved i guess.

Help needed!

The Module is loaded but it seems it does not fetchs any data.
It only says "ABFAHRTEN VON UNDEFINED" without any information below.

**Comment by docn85** [comment]
here is the config.js part:
```
{
            module: 'MMM-vvsDeparture',
            position: "top_left",
            config: {
                station_id: 'de:08111:6019',
                maximumEntries: 10,
             // station_name: 'Marienplatz',
             // reloadInterval: '1 * 60 * 1000'
                    }
},
```
I have a bad feeling when i think about to go back to MM 2.15 just to use the Module again.

**Comment by docn85** [comment]
issue has been soved
